# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_param xicom.use_bitstream_version_check 0
set_param tcl.collectionResultDisplayLimit 0
create_project -in_memory -part xczu9eg-ffvb1156-2-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/trungnguyen/01.IMPL/07.TDD_TEST/tdd_testing.cache/wt [current_project]
set_property parent.project_path /home/trungnguyen/01.IMPL/07.TDD_TEST/tdd_testing.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part xilinx.com:zcu102:part0:3.1 [current_project]
set_property ip_repo_paths /home/trungnguyen/01.IMPL/01.HDL/IPCORES/vttek/vt_orx_switch [current_project]
set_property ip_output_repo /home/trungnguyen/01.IMPL/07.TDD_TEST/tdd_testing.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  /home/trungnguyen/01.IMPL/07.TDD_TEST/tdd_simulation.vhd
  /home/trungnguyen/01.IMPL/07.TDD_TEST/dpd_cmd_simulation.vhd
  /home/trungnguyen/01.IMPL/07.TDD_TEST/tdd_testing.srcs/sources_1/bd/orx_test_bd/hdl/orx_test_bd_wrapper.vhd
}
add_files /home/trungnguyen/01.IMPL/07.TDD_TEST/tdd_testing.srcs/sources_1/bd/orx_test_bd/orx_test_bd.bd
set_property used_in_implementation false [get_files -all /home/trungnguyen/01.IMPL/07.TDD_TEST/tdd_testing.srcs/sources_1/bd/orx_test_bd/ip/orx_test_bd_proc_sys_reset_0_0/orx_test_bd_proc_sys_reset_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/trungnguyen/01.IMPL/07.TDD_TEST/tdd_testing.srcs/sources_1/bd/orx_test_bd/ip/orx_test_bd_proc_sys_reset_0_0/orx_test_bd_proc_sys_reset_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/trungnguyen/01.IMPL/07.TDD_TEST/tdd_testing.srcs/sources_1/bd/orx_test_bd/ip/orx_test_bd_proc_sys_reset_0_0/orx_test_bd_proc_sys_reset_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/trungnguyen/01.IMPL/07.TDD_TEST/tdd_testing.srcs/sources_1/bd/orx_test_bd/ip/orx_test_bd_util_ds_buf_0_0/orx_test_bd_util_ds_buf_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/trungnguyen/01.IMPL/07.TDD_TEST/tdd_testing.srcs/sources_1/bd/orx_test_bd/ip/orx_test_bd_system_ila_1_0/bd_2/ip/ip_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all /home/trungnguyen/01.IMPL/07.TDD_TEST/tdd_testing.srcs/sources_1/bd/orx_test_bd/ip/orx_test_bd_system_ila_1_0/bd_2/ip/ip_0/bd_33ae_ila_lib_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/trungnguyen/01.IMPL/07.TDD_TEST/tdd_testing.srcs/sources_1/bd/orx_test_bd/ip/orx_test_bd_system_ila_1_0/bd_2/bd_33ae_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/trungnguyen/01.IMPL/07.TDD_TEST/tdd_testing.srcs/sources_1/bd/orx_test_bd/ip/orx_test_bd_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all /home/trungnguyen/01.IMPL/07.TDD_TEST/tdd_testing.srcs/sources_1/bd/orx_test_bd/ip/orx_test_bd_system_ila_0_0/bd_0/ip/ip_0/bd_f3ff_ila_lib_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/trungnguyen/01.IMPL/07.TDD_TEST/tdd_testing.srcs/sources_1/bd/orx_test_bd/ip/orx_test_bd_system_ila_0_0/bd_0/bd_f3ff_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/trungnguyen/01.IMPL/07.TDD_TEST/tdd_testing.srcs/sources_1/bd/orx_test_bd/orx_test_bd_ooc.xdc]
set_property is_locked true [get_files /home/trungnguyen/01.IMPL/07.TDD_TEST/tdd_testing.srcs/sources_1/bd/orx_test_bd/orx_test_bd.bd]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/trungnguyen/01.IMPL/07.TDD_TEST/tdd_testing.srcs/constrs_1/new/location.xdc
set_property used_in_implementation false [get_files /home/trungnguyen/01.IMPL/07.TDD_TEST/tdd_testing.srcs/constrs_1/new/location.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top orx_test_bd_wrapper -part xczu9eg-ffvb1156-2-e -fsm_extraction gray


write_checkpoint -force -noxdef orx_test_bd_wrapper.dcp

catch { report_utilization -file orx_test_bd_wrapper_utilization_synth.rpt -pb orx_test_bd_wrapper_utilization_synth.pb }
