# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/location.xdc

# Block Designs: bd/orx_test_bd/orx_test_bd.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==orx_test_bd || ORIG_REF_NAME==orx_test_bd}]

# IP: bd/orx_test_bd/ip/orx_test_bd_proc_sys_reset_0_0/orx_test_bd_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==orx_test_bd_proc_sys_reset_0_0 || ORIG_REF_NAME==orx_test_bd_proc_sys_reset_0_0}]

# IP: bd/orx_test_bd/ip/orx_test_bd_xlconcat_0_0/orx_test_bd_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==orx_test_bd_xlconcat_0_0 || ORIG_REF_NAME==orx_test_bd_xlconcat_0_0}]

# IP: bd/orx_test_bd/ip/orx_test_bd_util_ds_buf_0_0/orx_test_bd_util_ds_buf_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==orx_test_bd_util_ds_buf_0_0 || ORIG_REF_NAME==orx_test_bd_util_ds_buf_0_0}]

# IP: bd/orx_test_bd/ip/orx_test_bd_vt_orx_switch_1_0/orx_test_bd_vt_orx_switch_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==orx_test_bd_vt_orx_switch_1_0 || ORIG_REF_NAME==orx_test_bd_vt_orx_switch_1_0}]

# IP: bd/orx_test_bd/ip/orx_test_bd_system_ila_1_0/orx_test_bd_system_ila_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==orx_test_bd_system_ila_1_0 || ORIG_REF_NAME==orx_test_bd_system_ila_1_0}]

# Block Designs: bd/orx_test_bd/ip/orx_test_bd_system_ila_1_0/bd_2/bd_33ae_0.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_33ae_0 || ORIG_REF_NAME==bd_33ae_0}]

# IP: bd/orx_test_bd/ip/orx_test_bd_system_ila_1_0/bd_2/ip/ip_0/bd_33ae_0_ila_lib_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_33ae_0_ila_lib_0 || ORIG_REF_NAME==bd_33ae_0_ila_lib_0}]

# IP: bd/orx_test_bd/ip/orx_test_bd_system_ila_1_0/bd_2/ip/ip_1/bd_33ae_0_g_inst_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_33ae_0_g_inst_0 || ORIG_REF_NAME==bd_33ae_0_g_inst_0}]

# IP: bd/orx_test_bd/ip/orx_test_bd_tdd_simulation_1_0/orx_test_bd_tdd_simulation_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==orx_test_bd_tdd_simulation_1_0 || ORIG_REF_NAME==orx_test_bd_tdd_simulation_1_0}]

# IP: bd/orx_test_bd/ip/orx_test_bd_dpd_cmd_simulation_0_0/orx_test_bd_dpd_cmd_simulation_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==orx_test_bd_dpd_cmd_simulation_0_0 || ORIG_REF_NAME==orx_test_bd_dpd_cmd_simulation_0_0}]

# IP: bd/orx_test_bd/ip/orx_test_bd_system_ila_2_0/orx_test_bd_system_ila_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==orx_test_bd_system_ila_2_0 || ORIG_REF_NAME==orx_test_bd_system_ila_2_0}]

# Block Designs: bd/orx_test_bd/ip/orx_test_bd_system_ila_2_0/bd_0/bd_335e.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_335e || ORIG_REF_NAME==bd_335e}]

# IP: bd/orx_test_bd/ip/orx_test_bd_system_ila_2_0/bd_0/ip/ip_0/bd_335e_ila_lib_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_335e_ila_lib_0 || ORIG_REF_NAME==bd_335e_ila_lib_0}]

# IP: bd/orx_test_bd/ip/orx_test_bd_system_ila_2_0/bd_0/ip/ip_1/bd_335e_g_inst_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_335e_g_inst_0 || ORIG_REF_NAME==bd_335e_g_inst_0}]

# IP: bd/orx_test_bd/ip/orx_test_bd_xlconstant_0_1/orx_test_bd_xlconstant_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==orx_test_bd_xlconstant_0_1 || ORIG_REF_NAME==orx_test_bd_xlconstant_0_1}]

# IP: bd/orx_test_bd/ip/orx_test_bd_ic0_0/orx_test_bd_ic0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==orx_test_bd_ic0_0 || ORIG_REF_NAME==orx_test_bd_ic0_0}]

# IP: bd/orx_test_bd/ip/orx_test_bd_ic0_1/orx_test_bd_ic0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==orx_test_bd_ic0_1 || ORIG_REF_NAME==orx_test_bd_ic0_1}]

# IP: bd/orx_test_bd/ip/orx_test_bd_ic2_0/orx_test_bd_ic2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==orx_test_bd_ic2_0 || ORIG_REF_NAME==orx_test_bd_ic2_0}]

# XDC: bd/orx_test_bd/ip/orx_test_bd_proc_sys_reset_0_0/orx_test_bd_proc_sys_reset_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==orx_test_bd_proc_sys_reset_0_0 || ORIG_REF_NAME==orx_test_bd_proc_sys_reset_0_0}] {/U0 }]/U0 ]]

# XDC: bd/orx_test_bd/ip/orx_test_bd_proc_sys_reset_0_0/orx_test_bd_proc_sys_reset_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==orx_test_bd_proc_sys_reset_0_0 || ORIG_REF_NAME==orx_test_bd_proc_sys_reset_0_0}] {/U0 }]/U0 ]]

# XDC: bd/orx_test_bd/ip/orx_test_bd_proc_sys_reset_0_0/orx_test_bd_proc_sys_reset_0_0_ooc.xdc

# XDC: bd/orx_test_bd/ip/orx_test_bd_util_ds_buf_0_0/orx_test_bd_util_ds_buf_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==orx_test_bd_util_ds_buf_0_0 || ORIG_REF_NAME==orx_test_bd_util_ds_buf_0_0}] {/U0 }]/U0 ]]

# XDC: bd/orx_test_bd/ip/orx_test_bd_system_ila_1_0/bd_2/ip/ip_0/ila_v6_2/constraints/ila.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_33ae_0_ila_lib_0 || ORIG_REF_NAME==bd_33ae_0_ila_lib_0}] {/U0 }]/U0 ]]

# XDC: bd/orx_test_bd/ip/orx_test_bd_system_ila_1_0/bd_2/ip/ip_0/bd_33ae_0_ila_lib_0_ooc.xdc

# XDC: bd/orx_test_bd/ip/orx_test_bd_system_ila_1_0/bd_2/bd_33ae_0_ooc.xdc

# XDC: bd/orx_test_bd/ip/orx_test_bd_system_ila_2_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_335e_ila_lib_0 || ORIG_REF_NAME==bd_335e_ila_lib_0}] {/U0 }]/U0 ]]

# XDC: bd/orx_test_bd/ip/orx_test_bd_system_ila_2_0/bd_0/ip/ip_0/bd_335e_ila_lib_0_ooc.xdc

# XDC: bd/orx_test_bd/ip/orx_test_bd_system_ila_2_0/bd_0/bd_335e_ooc.xdc

# XDC: bd/orx_test_bd/orx_test_bd_ooc.xdc
